# Generated by Django 4.2.1 on 2023-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='founded_at',
        ),
        migrations.AddField(
            model_name='team',
            name='first_cup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
